### ISSUE TITLE
Having multiple images doesn't trigger the tap listener for the first image

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#396]
### Expected
When the user inserts multiple images on a given Post, tapping on any of the images should be handled correctly (i.e. should show the  "stop uploading?"  popup if it's uploading or enqueued, or show the image settings modal screen if it's already uploaded).

### Observed
When inserting 2 images, tapping on the first image doesn't do anything, and debugging shows `onImageTapped()` is not getting called.

### Reproduced
1. Start a new draft
2. Start the media picker to include an image, by tapping on the "+" icon in the toolbar
3. insert 2 images, either by choosing one each time, or by selecting 2 images in the same image picker action 
4. tap on the first image
5. observe that nothing happens

#### Tested
[Google Pixel] on [7.1.2] with [WPAndroid `alpha-61`, `release/7.7` and `develop`]

**Comment by khaykov** [comment]
Looks like it got fixed in [this](https://github.com/wordpress-mobile/WordPress-Android/pull/6208) PR.

**Comment by mzorz** [comment]
I'm still seeing this issue with latest Aztec `develop` as described in [this comment here](https://github.com/wordpress-mobile/WordPress-Android/pull/6254#issuecomment-314527756)

**Comment by mzorz** [comment]
I confirm I'm still seeing this issue on latest Aztec `develop` branch when integrated with WPAndroid (using this line in build.gradle `compile ('com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:develop-SNAPSHOT’)`)

**Comment by 0nko** [comment]
I can reproduce this, as well.

**Comment by prasad456** [comment]
i'm unable to get file from the path to upload the image to server
