### ISSUE TITLE
Cursor can not move to image start.

### ISSUE THREAD

**Issue by liufsd** [wordpress-mobile/AztecEditor-Android#513]
hi~
when i insert a max width image . the Cursor can not move to this line end.
![image](https://user-images.githubusercontent.com/1910405/32223422-4c43c5f2-be0b-11e7-96a9-c28aa738925f.png)
(can not move the cursor to the position after 'n')

how to fix this issue?

**Comment by liufsd** [comment]
and also can not select this line text before image.
![image](https://user-images.githubusercontent.com/1910405/32223695-61f5348e-be0c-11e7-8c2b-f3daeec20ece.png)

(build by last source code)

**Comment by 0nko** [comment]
This is a known issue and is related to #327.

**Comment by daniloercoli** [comment]
Fixed in #525

**Comment by liufsd** [comment]
sorry . not fixed.
test:
input "hello"
and then, insert image
you will see this issue again.

**Comment by liufsd** [comment]
```
    fun insertImage(drawable: Drawable?, attributes: Attributes, onImageTappedListener: OnImageTappedListener?,
                    onMediaDeletedListener: AztecText.OnMediaDeletedListener?) {
        val nestingLevel = IAztecNestable.getNestingLevelAt(editableText, selectionStart)
        val span = AztecImageSpan(editor.context, drawable, nestingLevel, AztecAttributes(attributes), onImageTappedListener,
                onMediaDeletedListener, editor)
        insertMedia(span)
    }
```

The 'nestingLevel' return 0. 
you can also test insert a image in some text. such as:
input 'hello', and then insert a image before 'e'.

**Comment by liufsd** [comment]
Any answer about this ?
i think, insert a image in the some text. we must insert a new line before image tag.
